### ISSUE TITLE
JAX dct is not accurate compared to scipy

### ISSUE THREAD

**Issue by unalmis** [jax-ml/jax#23895] opened 2024-09-25 00:09 UTC
I have also found Jax's dct to be inaccurate compared to scipy: https://github.com/PlasmaControl/DESC/pull/1119/files#r1774234361, >= ~8 orders of magnitude even on 64 bit floating point mode.

To see this just change
```python
# Uses Jax
fq_2 = norm * idct(dct(f(m), type=dct_type), n=n.size, type=dct_type)
```
to 
```python
# Uses scipy
fq_2 = norm * sidct(sdct(f(m), type=dct_type), n=n.size, type=dct_type)
```
and observe
```python
# JAX is less accurate than scipy.
factor = 1e8 if using_jax else 1
np.testing.assert_allclose(fq_2, f(n), atol=1e-14 * factor)
```

_Originally posted by @unalmis in https://github.com/jax-ml/jax/issues/23827#issuecomment-2372595040_

**Comment by jakevdp** [comment] 2024-09-25 00:32
Hi, thanks for the report! Could you put together a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) demonstrating the issue? That will prevent us from having to guess at what the problematic inputs might be. Thanks!

**Comment by unalmis** [comment] 2024-09-25 00:57
Here is the the more mwe from https://github.com/PlasmaControl/DESC/pull/1119#discussion_r1774234361. You may run with `pytest -k test_dct` or you can provide the inputs to the function manually.

```python

import jax.numpy as jnp
from jax.scipy.fft import dct, idct
from scipy.fft import dct as sdct
from scipy.fft import idct as sidct
import pytest

jax_config.update("jax_enable_x64", True)



def cheb_pts(N):
    n = jnp.arange(N)
    return jnp.cos(jnp.pi * (2 * n + 1) / (2 * N))


def _identity(x):
    return x

@pytest.mark.unit
@pytest.mark.parametrize(
    "f, M",
    [
        (_identity, 2),
        (_identity, 3),
    ],
)
def test_dct(f, M):
    # Need to test fft used in Fourier Chebyshev interpolation due to issues like
    # https://github.com/scipy/scipy/issues/15033
    # https://github.com/scipy/scipy/issues/21198
    # https://github.com/google/jax/issues/22466.
    m = cheb_pts(M)
    n = cheb_pts(m.size * 10)
    norm = n.size / m.size

    dct_type = 2
    np.testing.assert_allclose(norm * sidct(sdct(f(m), type=dct_type), n=n.size, type=dct_type), f(n), atol=1e-14)
    # JAX is less accurate than scipy.
    np.testing.assert_allclose(norm * idct(dct(f(m), type=dct_type), n=n.size, type=dct_type), f(n), atol=1e-14)
```

**Comment by jakevdp** [comment] 2024-09-25 16:05
Since `dct` calls `fft`, I suspect this may be a duplicate of https://github.com/jax-ml/jax/issues/23827.

**Comment by unalmis** [comment] 2024-09-25 16:20
Yes this issue was raised from that thread. However I made a new issue because this test fails regardless of hardware. For me it is 8 orders less accurate on cpu.

**Comment by dfm** [comment] 2024-09-25 16:58
This issue was actually unrelated to https://github.com/jax-ml/jax/issues/23827, but the fix was straightforward: https://github.com/jax-ml/jax/pull/23917

**Closed** 2024-09-25 17:41 UTC
