### ISSUE TITLE
Memory leak in id_tap on TPU

### ISSUE THREAD

**Issue by sbodenstein** [jax-ml/jax#5927] opened 2021-03-04 13:03 UTC
There seems to be a memory leak using `id_tap` on TPU (I don't see memory increasing with either `cpu` or `gpu` backends). Also, this only taps out 1 million scalars, but starts taking gigabytes of memory:
```
import jax
import jax.numpy as jnp
from jax.experimental import host_callback
import psutil

def call_back(x, y):
  return 

def inside(x, _):
  x = x + 1.2
  x = host_callback.id_tap(call_back, x)
  return x, 1

def forward(x, n):
  x = jax.lax.scan(inside, x, None, length=n)
  return x

n = 10000
f = jax.jit(forward, static_argnums=1, backend='tpu')
x = jnp.array(2.3)

for i in range(100):
  f(x, n)
  host_callback.barrier_wait()
  if i % 10 == 0:
    print('memory used', psutil.virtual_memory().used / 10**9) # in GB
  
  
# memory used 7.073148928
# memory used 9.067659264
# memory used 10.378866688
# memory used 11.012489216
# memory used 11.18887936
# memory used 11.542859776
# memory used 12.166238208
# memory used 12.44387328
# memory used 13.055688704
# memory used 13.506678784
```

**Comment by sbodenstein** [comment] 2021-03-17 09:06
Any update about this? Its currently preventing us logging out activation statistics during training.

**Comment by gnecula** [comment] 2021-03-18 09:04
I have started to look into this. I can reproduce the problem. It seems that this is not due to host_callback, but is a behavior of the TPU runtime. This is in part suggested by the fact that the problem does not appear for CPU and GPU. My best guess is that the TPU runtime buffers the outfeed from the device faster than the CPU thread can consume them. (This is not a problem for CPU and GPU because the outfeed blocks the device until the outfeed consumer takes the outfeed.) This does not fully explain the problem, it also seems that the TPU runtime does not reuse the outfeed buffers eagerly enough and keeps allocating more memory.  

If I run your example with a repeat factor of 300 instead of 100, I see that the memory grows to 18Gb and then plateaus. The starting memory usage is 9Gb. Why the TPU runtime allocates such a big buffer, I do not know. I am wondering if this is expected behavior if there is memory available. Do you actually see the memory growing unboundedly? 

I have done another experiment, where I replaced host_callback with straight outfeed and I see the same memory behavior.

**Comment by sbodenstein** [comment] 2021-03-18 10:40
> Do you actually see the memory growing unboundedly?
I don't actually!

> My best guess is that the TPU runtime buffers the outfeed from the device faster than the CPU thread can consume them.
But the example sends a million scalars, which should take ~megabyte at most in the buffer. How can it be taking gigabytes? That must be a bug somewhere in the allocator?

**Comment by gnecula** [comment] 2021-03-18 10:57
I think that each computation sends 10k float32. I am pretty sure that on TPU the smallest buffer for outfeed is 1k. So, each computation uses up 10Mb in the worst case if the TPU does all the outfeeds before the host consumes any of them. What I do not understand is why this memory is not reused for the second iteration of the computation. 

If after 200 iterations we see a growth of 10Gb, this suggests that the growth is 50Mb per iteration, a factor of 5x over the one I expect.

**Comment by sbodenstein** [comment] 2021-03-18 11:07
Ah ok that is interesting to know that there is a minimum buffer size. 

Also, the memory check is happening after `host_callback.barrier_wait()`. So the buffer is empty at this point. It definitely shouldn't keep growing after every iteration, as you say!

**Comment by sbodenstein** [comment] 2022-04-20 09:43
Any updates about this? Is this maybe something to report to the TPU runtime team?

**Comment by gnecula** [comment] 2022-05-04 12:27
@zhangqiaorjc This seems to be a TPU runtime issue. Do you know who we can ask to help?

**Comment by rajasekharporeddy** [comment] 2024-04-08 16:55
Hi @sbodenstein 

Looks like this issue has been resolved in later versions of JAX. I executed the mentioned code with JAX version 0.4.23 on Colab TPU v2. Since jax.experimental.host_callback is deprecated (https://github.com/google/jax/issues/20385), I have used `jax.experimental.io_callback` instead of `jax.experimental.host_callback.id_tap` and `jax.effects_barrier` instead of `jax.experimental.host_callback.barrier_wait` as mentioned in #20385 and it didn't produce any memory leak issue.

```python
import jax
import jax.numpy as jnp
from jax.experimental import io_callback, host_callback
import psutil

def call_back(x, y):
  return 

def inside(x, _):
  x = x + 1.2
  x = io_callback(call_back, x)
  return x, 1

def forward(x, n):
  x = jax.lax.scan(inside, x, None, length=n)
  return x

n = 10000
f = jax.jit(forward, static_argnums=1, backend='tpu')
x = jnp.array(2.3)

for i in range(500):
  f(x, n)
  jax.effects_barrier
  if i % 10 == 0:
    print('memory used', psutil.virtual_memory().used / 10**9) # in GB
```
Output:
```
memory used 3.814080512
memory used 3.823570944
memory used 3.825119232
memory used 3.825618944
memory used 3.816890368
memory used 3.790503936
memory used 3.774885888
memory used 3.769438208
memory used 3.769704448
memory used 3.758534656
memory used 3.759980544
memory used 3.759153152
memory used 3.791003648
memory used 3.788177408
memory used 3.79998208
memory used 3.784126464
memory used 3.776905216
memory used 3.770011648
memory used 3.777855488
memory used 3.767222272
memory used 3.754917888
memory used 3.760549888
memory used 3.757154304
memory used 3.775848448
memory used 3.797016576
memory used 3.779903488
memory used 3.786407936
memory used 3.780775936
memory used 3.771588608
memory used 3.762327552
memory used 3.769225216
memory used 3.764793344
memory used 3.774472192
memory used 3.765661696
memory used 3.767939072
memory used 3.778342912
memory used 3.778920448
memory used 3.796463616
memory used 3.780620288
memory used 3.786207232
memory used 3.771101184
memory used 3.792674816
memory used 3.810402304
memory used 3.790241792
memory used 3.804946432
memory used 3.813400576
memory used 3.821871104
memory used 3.820371968
memory used 3.827765248
memory used 3.831394304
```

Please find the [gist](https://colab.sandbox.google.com/gist/rajasekharporeddy/87af0d235bab4f2a0ee707885ec65605/-5927.ipynb) for reference.

Thank you

**Comment by hawkinsp** [comment] 2024-11-14 00:34
id_tap has been removed from JAX, so this issue should be moot.

**Closed by hawkinsp** 2024-11-14 00:34 UTC
Labels: bug
