### ISSUE TITLE
argmax returns incorrect result for input containing -0.0 (JAX)

### ISSUE THREAD

**Issue by LilyDong0127** [jax-ml/jax#24281] opened 2024-10-14 10:19 UTC
### Description

Description:
When using jnp.argmax with an input array containing -0.0, the result is incorrect. Specifically, the function returns 1 (the index of -0.0) as the position of the maximum value, while the actual maximum value is 1.401298464324817e-45 at index 2.

This issue is reproducible in TensorFlow and Keras as well, as they share similar backend logic for the argmax function. However, PyTorch correctly returns the expected index 2 for the maximum value.

Expected Behavior:
jnp.argmax should return 2, as the value at index 2 (1.401298464324817e-45) is greater than both -1.0 and -0.0.
```
import numpy as np
import torch
import tensorflow as tf
import jax.numpy as jnp
from tensorflow import keras

def test_argmax():
    # Input data
    input_data = np.array([-1.0, -0.0, 1.401298464324817e-45], dtype=np.float32)

    # PyTorch argmax
    pytorch_result = torch.argmax(torch.tensor(input_data, dtype=torch.float32)).item()
    print(f"PyTorch argmax result: {pytorch_result}")

    # TensorFlow argmax
    tensorflow_result = tf.math.argmax(input_data).numpy()
    print(f"TensorFlow argmax result: {tensorflow_result}")

    # Keras argmax (Keras internally uses TensorFlow, so should be the same)
    keras_result = keras.backend.argmax(input_data).numpy()
    print(f"Keras argmax result: {keras_result}")

    # JAX argmax
    jax_result = jnp.argmax(input_data)
    print(f"JAX argmax result: {jax_result}")

if __name__ == "__main__":
    test_argmax()

```

### System info (python version, jaxlib version, accelerator, etc.)

```
PyTorch argmax result: 2
TensorFlow argmax result: 1
Keras argmax result: 1
JAX argmax result: 1

```
Additional Notes:
This issue arises when the input contains -0.0. It seems that JAX incorrectly treats -0.0 as greater than 1.401298464324817e-45, which is logically incorrect. This discrepancy needs to be addressed for argmax to work as expected.

**Comment by pearu** [comment] 2024-10-14 10:23
This is not `argmax` issue, see https://github.com/jax-ml/jax/issues/24280#issuecomment-2410724204 for an explanation.

**Comment by LilyDong0127** [comment] 2024-10-14 10:33
> 这不是`argmax`问题，请参阅[#24280（评论）](https://github.com/jax-ml/jax/issues/24280#issuecomment-2410724204)了解解释。
PyTorch and JAX were both run on the same CPU: The issue is not CPU-specific because PyTorch, running on the same CPU, produced the correct argsort result. PyTorch correctly treats -0.0 and 0.0 as equal in sorting, as per IEEE 754 standards. JAX, however, fails to do so, resulting in incorrect argsort behavior.

Incorrect sorting behavior for -0.0: In my provided test case, JAX's argsort incorrectly places -0.0 in a different order compared to 0.0. According to IEEE 754, -0.0 and 0.0 should be considered equal, but JAX does not conform to this, leading to unexpected results. PyTorch, on the other hand, produces the expected sorting order, handling -0.0 and 0.0 equivalently.

FTZ mode is not the root cause: While FTZ mode on CPUs can explain the handling of subnormal numbers like 1.401298464324817e-45, this issue fundamentally relates to how JAX differentiates between -0.0 and 0.0 in its sorting operations. The key problem is that JAX's argsort treats -0.0 as different from 0.0, which is incorrect based on floating-point standards.

**Comment by jakevdp** [comment] 2024-10-14 12:44
> The key problem is that JAX's argsort treats -0.0 as different from 0.0, which is incorrect based on floating-point standards.

Can you give a specific example of where JAX treats -0.0 as different from 0.0? I don't see this in the case of `argsort` or `argmax`. For example:
```python
>>> x1 = jnp.array([0.0, -0.0])
>>> x2 = jnp.array([-0.0, 0.0])

# Confirm with signbit that the signed zeros are present:
>>> jnp.signbit(x1)
Array([False,  True], dtype=bool)\
>>> jnp.signbit(x2)
Array([ True, False], dtype=bool)

# compare argmax:
>>> jnp.argmax(x1)
Array(0, dtype=int32)
>>> jnp.argmax(x2)
Array(0, dtype=int32)

# compare argsort:
>>> jnp.argsort(x1)
Array([0, 1], dtype=int32)
>>> jnp.argsort(x2)
Array([0, 1], dtype=int32)
```

**Comment by LilyDong0127** [comment] 2024-10-14 12:59
> > The key problem is that JAX's argsort treats -0.0 as different from 0.0, which is incorrect based on floating-point standards.
> 
> Can you give a specific example of where JAX treats -0.0 as different from 0.0? I don't see this in the case of `argsort` or `argmax`. For example:
> 
> ```python
> >>> x1 = jnp.array([0.0, -0.0])
> >>> x2 = jnp.array([-0.0, 0.0])
> 
> # Confirm with signbit that the signed zeros are present:
> >>> jnp.signbit(x1)
> Array([False,  True], dtype=bool)
> >>> jnp.signbit(x2)
> Array([ True, False], dtype=bool)
> 
> # compare argmax:
> >>> jnp.argmax(x1)
> Array(0, dtype=int32)
> >>> jnp.argmax(x2)
> Array(0, dtype=int32)
> 
> # compare argsort:
> >>> jnp.argsort(x1)
> Array([0, 1], dtype=int32)
> >>> jnp.argsort(x2)
> Array([0, 1], dtype=int32)
> ```

Thanks for your response. I understand that the issue might not be about the difference between 0.0 and -0.0 directly. However, the core of my concern is why the results between CPU and GPU are not consistent. This discrepancy is most noticeable when using argsort in JAX, where the results are different on CPU and GPU, likely due to how small numbers like subnormals are handled.

PyTorch consistently provides correct and matching results across CPU and GPU, while JAX does not. The fact that this inconsistency exists in JAX but not in PyTorch is what suggests there's a deeper issue, particularly with how JAX handles very small numbers and how those get "flushed to zero" under certain hardware configurations. Could we explore why JAX shows this discrepancy while other frameworks do not?

**Comment by jakevdp** [comment] 2024-10-14 13:03
OK – since we've confirmed that JAX handles 0.0 and -0.0 equivalently on all platforms, it seems your main contention is with handling of subnormals. Given that, I'm going to close this as a duplicate of #24280 where you've raised the same issue.

**Closed by jakevdp** 2024-10-14 13:03 UTC
Labels: bug
