### ISSUE TITLE
np.size on jax._src.stages.ArgInfo 

### ISSUE THREAD

**Issue by Joshuaalbert** [jax-ml/jax#24676] opened 2024-11-02 17:40 UTC
### Description

I'm not sure of the origin of ArgInfo, but I'm getting it while AOT compiling in a multi-host setting. My shape and size checks failed mysteriously and then I found that arrays were being seen as `jax._src.stages.ArgInfo` objects during tracing. Furthermore, np.size(x) doesn't match np.prod(np.shape(x)) on these objects.

### System info (python version, jaxlib version, accelerator, etc.)

jax:    0.4.33
jaxlib: 0.4.33
numpy:  1.26.4
python: 3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0]
jax.devices (1 total, 1 local): [CudaDevice(id=0)]
process_count: 1
platform: uname_result(system='Linux', node='mario', release='4.18.0-425.13.1.el8_7.x86_64', version='#1 SMP Thu Feb 2 13:01:45 EST 2023', machine='x86_64')

$ nvidia-smi
Sat Nov  2 10:40:26 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090         Off| 00000000:01:00.0 Off |                  N/A |
| 30%   35C    P2               82W / 350W|    258MiB / 24576MiB |      2%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A   3628097      C   python                                      256MiB |
+---------------------------------------------------------------------------------------+

**Comment by yashk2810** [comment] 2024-11-02 17:42
Can you give a minimal repro of the failure and your usage of AOT APIs?

**Comment by Joshuaalbert** [comment] 2024-11-02 18:57
Okay, a simple attempt at making a MVCE was unable to reproduce the error. So that tends to mean the root cause is something other than what I think. In my code it's most definitely occuring at this line:

```python
run_process_jit_compiled = jax.jit(run_process).lower(run_key, init.params, init.states, num_steps=1).compile()
```

where, `run_key` is a prng key, `init.params` and `init.states` are classes registered as pytrees, and `num_steps` is in `static_argnames`. The function runs without `jit` compiling.

 I would encourage looking at the code, where `ArgInfo` is introduced and how it could be there during tracing. Perhaps you can explain what `ArgInfo` is?

**Comment by yashk2810** [comment] 2024-11-02 20:45
Can you atleast paste the traceback? Even that would be good information to understand what's going on.

**Comment by Joshuaalbert** [comment] 2024-11-02 22:56
Here it is with traceback filtering off.
```
Traceback (most recent call last):
  File "/fastpool/albert/git/DSA2000-Cal/dsa2000_cal/scripts/streaming_forward_modelling/launch_process.py", line 45, in <module>
    main(1, 0, f"localhost:{port}", 'plots')
  File "/fastpool/albert/git/DSA2000-Cal/dsa2000_cal/scripts/streaming_forward_modelling/launch_process.py", line 34, in main
    process_start(
  File "/home/albert/miniconda3/envs/dsa_py/lib/python3.11/site-packages/dsa2000_cal/forward_models/streaming/process.py", line 313, in process_start
    run_process_jit_compiled = run_process_jit.lower(run_key, init.params, init.states, num_steps=1).compile()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albert/miniconda3/envs/dsa_py/lib/python3.11/site-packages/jax/_src/traceback_util.py", line 180, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/albert/miniconda3/envs/dsa_py/lib/python3.11/site-packages/jax/_src/pjit.py", line 478, in lower
    traced = trace(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albert/miniconda3/envs/dsa_py/lib/python3.11/site-packages/jax/_src/traceback_util.py", line 180, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/albert/miniconda3/envs/dsa_py/lib/python3.11/site-packages/jax/_src/pjit.py", line 503, in trace
    args_info = stages.make_args_info(p.in_tree, p.in_avals, donate_argnums)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albert/miniconda3/envs/dsa_py/lib/python3.11/site-packages/jax/_src/stages.py", line 403, in make_args_info
    return in_tree.unflatten([
           ^^^^^^^^^^^^^^^^^^^
  File "/home/albert/miniconda3/envs/dsa_py/lib/python3.11/site-packages/dsa2000_cal/common/interp_utils.py", line 550, in interpolated_array_unflatten
    return InterpolatedArray(x=x, values=values, axis=axis, regular_grid=regular_grid, check_spacing=check_spacing,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/dataclasses.py", line 293, in pydantic.dataclasses._add_pydantic_validation_attributes.handle_extra_init
    self.init = init
  File "<string>", line 11, in __init__
  File "pydantic/dataclasses.py", line 312, in pydantic.dataclasses._add_pydantic_validation_attributes.new_post_init
    f'hash={self.hash!r},'
  File "/home/albert/miniconda3/envs/dsa_py/lib/python3.11/site-packages/dsa2000_cal/common/interp_utils.py", line 413, in __post_init__
    jax.tree.map(_assert_shape, self.values)
  File "/home/albert/miniconda3/envs/dsa_py/lib/python3.11/site-packages/jax/_src/tree.py", line 155, in map
    return tree_util.tree_map(f, tree, *rest, is_leaf=is_leaf)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albert/miniconda3/envs/dsa_py/lib/python3.11/site-packages/jax/_src/tree_util.py", line 344, in tree_map
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albert/miniconda3/envs/dsa_py/lib/python3.11/site-packages/jax/_src/tree_util.py", line 344, in <genexpr>
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
                             ^^^^^^
  File "/home/albert/miniconda3/envs/dsa_py/lib/python3.11/site-packages/dsa2000_cal/common/interp_utils.py", line 410, in _assert_shape
    raise ValueError(f"Input values must have size x {np.shape(self.x)} on `axis` dimension ({self.axis}), got value shape {np.shape(x)}. "
ValueError: Input values must have size x (157,) on `axis` dimension (-1), got value shape (2048, 3, 157). 157 != 1
```

**Comment by yashk2810** [comment] 2024-11-03 21:02
This tells me that the problem is in your code. `ArgInfo` is not used during tracing. It's just used to create an internal datastructure to track some stuff: https://cs.opensource.google/jax/jax/+/main:jax/_src/stages.py;l=400-405?q=stages.py&ss=jax%2Fjax

I am closing this issue. Please reopen if you can reproduce this issue minimally in pure JAX and I'll look into a fix.

**Closed by yashk2810** 2024-11-03 21:02 UTC
Labels: bug

**Comment by Joshuaalbert** [comment] 2024-11-04 00:27
Can we reopen until this is resolved? I sense that this is deeper than something wrong with my code. I will try to sort out where this can be happening in JAX myself, and leave notes. If you have time, it would be great to get your comments on my observation. When I bisect where this is happening in JAX land then perhaps I can make a better MVCE. 

1. `stages.make_args_info` looks like this:

```
def make_args_info(in_tree, in_avals, donate_argnums):
  donate_argnums = frozenset(donate_argnums)
  flat_avals, _ = tree_util.tree_flatten(in_avals)  # todo: remove
  return in_tree.unflatten([
      ArgInfo(aval, i in donate_argnums)
      for i, aval in enumerate(flat_avals)])
```

The problem is `in_tree.unflatten([ArgInfo(aval, i in donate_argnums) for i, aval in enumerate(flat_avals)])` because you're relying when you unflatten code to only make use of shape and dtype. However, in a registered pytree this is not always the case, e.g. if shape checks are performed etc.

I think now we have enough to make a MVCE.


```python
import dataclasses

import jax
import jax.numpy as jnp
import numpy as np


@dataclasses.dataclass
class Pytree:
    x: jax.Array
    values: jax.Array
    axis: int

    def __post_init__(self):
        assert np.shape(self.values)[self.axis] == np.size(self.x)


def pytree_flatten(p: Pytree):
    return (
        [p.x, p.values],
        (p.axis,)
    )


def pytree_unflatten(aux_data, children):
    x, values = children
    axis, = aux_data
    return Pytree(x, values, axis)


jax.tree_util.register_pytree_node(
    Pytree,
    pytree_flatten,
    pytree_unflatten
)


def f(p: Pytree):
    return p


def main():
    x = jnp.ones(5)
    values = jnp.ones((10, 5))
    axis = -1
    p = Pytree(x, values, axis)
    jax.block_until_ready(f(p))
    jax.block_until_ready(jax.jit(f)(p))

    jax.jit(f).lower(p).compile()


if __name__ == '__main__':
    main()
```

**Comment by Joshuaalbert** [comment] 2024-11-04 00:27
@yashk2810 made a MVCE^

**Comment by Joshuaalbert** [comment] 2024-11-04 00:38
I think it means if you intend for a consistent pytree system, i.e. should in all cases as long as the flattening and unflattening is a bijection, then you should at least implement `ndim` and `size` for `ArgInfo`.

**Comment by yashk2810** [comment] 2024-11-04 00:38
If you perform shape checks, then it's up to you to make that work. JAX does not guarantee for such checks to keep working. We can unflatten with any object we want so it's not recommended to do such checks.

If you want, you can tree_map and check later.

**Comment by Joshuaalbert** [comment] 2024-11-04 00:44
I see, makes sense. So if users want to do such checks, they presume the class won't be unflattened with some different objects. So in this case it makes most sense to simple not use np.size or such things, but assume only dtype and shape are available.

Btw, is this states in the documentation on registering pytrees? Might be helpful to future people.

**Comment by yashk2810** [comment] 2024-11-04 00:49
Yup, it's already documented here: https://jax.readthedocs.io/en/latest/working-with-pytrees.html#custom-pytrees-and-initialization-with-unexpected-values

> but assume only dtype and shape are available.

No, even these may not be available.

**Comment by Joshuaalbert** [comment] 2024-11-04 01:11
Okay, well in this case I my solution is to add a `skip_post_init` flag. The post_init is only necessary at initial creation time, not for flattening.

```python

@dataclasses.dataclass
class Pytree:
    x: jax.Array
    values: jax.Array
    axis: int
    skip_post_init: bool = False

    def __post_init__(self):
        if skip_post_init:
            return
        assert np.shape(self.values)[self.axis] == np.size(self.x)


def pytree_flatten(p: Pytree):
    return (
        [p.x, p.values],
        (p.axis,)
    )


def pytree_unflatten(aux_data, children):
    x, values = children
    axis, = aux_data
    return Pytree(x, values, axis, skip_post_init=True)


jax.tree_util.register_pytree_node(
    Pytree,
    pytree_flatten,
    pytree_unflatten
)
```
