### ISSUE TITLE
`jax.lax.dot_general`: getting `failed to legalize operation 'vhlo.dot_general_v2' that was explicitly marked illegal`

### ISSUE THREAD

**Issue by andportnoy** [jax-ml/jax#24648] opened 2024-10-31 21:02 UTC
### Description

Repro:

```python
import jax
import jax.numpy as jnp
import jax.random as jr

in_dtype = jnp.dtype(jnp.float16)
out_dtype = jnp.dtype(jnp.float32)
m = k = n = 1024

kx, ky = jr.split(jr.key(1234))
x = jr.uniform(kx, (m, k), dtype=in_dtype)
y = jr.uniform(ky, (k, n), dtype=in_dtype)

jax.lax.dot_general(
    x,
    y,
    dimension_numbers=(((1,), (0,)), ((), ())),
    precision=jax.lax.DotAlgorithm(
        lhs_precision_type=in_dtype,
        rhs_precision_type=in_dtype,
        accumulation_type=jnp.float32,
    ),
    preferred_element_type=out_dtype,
)
```
Error:
```
Traceback (most recent call last):
  File "/opt/jax/jax/experimental/mosaic/gpu/examples/test.py", line 13, in <module>
    jax.lax.dot_general(
  File "/opt/jax/jax/_src/lax/lax.py", line 1108, in dot_general
    return dot_general_p.bind(lhs, rhs,
  File "/opt/jax/jax/_src/core.py", line 442, in bind
    return self.bind_with_trace(cur_trace, args, params)
  File "/opt/jax/jax/_src/core.py", line 445, in bind_with_trace
    return trace.process_primitive(self, args, params)
  File "/opt/jax/jax/_src/core.py", line 905, in process_primitive
    return primitive.impl(*args, **params)
  File "/opt/jax/jax/_src/dispatch.py", line 90, in apply_primitive
    outs = fun(*args)
jaxlib.xla_extension.XlaRuntimeError: INVALID_ARGUMENT: Failed to serialize StableHLO;

Detailed error from MLIR: <unknown>:0: error: loc("jit(dot_general)/jit(main)/dot_general"): failed to legalize operation 'vhlo.dot_general_v2' that was explicitly marked illegal
<unknown>:0: note: loc("jit(dot_general)/jit(main)/dot_general"): see current operation: %0 = "vhlo.dot_general_v2"(%arg0, %arg1) <{accumulation_type = #vhlo.type_v1<!vhlo.f32_v1>, allow_imprecise_accumulation = #vhlo.bool_v1<false>, lhs_batching_dimensions = #vhlo.tensor_v1<dense<> : tensor<0xi64>>, lhs_component_count = #vhlo.integer_v1<1 : i64>, lhs_contracting_dimensions = #vhlo.tensor_v1<dense<1> : tensor<1xi64>>, lhs_precision_type = #vhlo.type_v1<!vhlo.f16_v1>, num_primitive_operations = #vhlo.integer_v1<1 : i64>, precision_config = #vhlo.array_v1<[#vhlo<precision_v1 DEFAULT>, #vhlo<precision_v1 DEFAULT>]>, rhs_batching_dimensions = #vhlo.tensor_v1<dense<> : tensor<0xi64>>, rhs_component_count = #vhlo.integer_v1<1 : i64>, rhs_contracting_dimensions = #vhlo.tensor_v1<dense<0> : tensor<1xi64>>, rhs_precision_type = #vhlo.type_v1<!vhlo.f16_v1>}> : (!vhlo.tensor_v1<1024x1024x!vhlo.f16_v1>, !vhlo.tensor_v1<1024x1024x!vhlo.f16_v1>) -> !vhlo.tensor_v1<1024x1024x!vhlo.f32_v1>
<unknown>:0: error: failed to convert VHLO to v1.4.0
<unknown>:0: note: see current operation: 
"builtin.module"() <{sym_name = "jit_dot_general"}> ({
  "vhlo.func_v1"() <{arg_attrs = #vhlo.array_v1<[#vhlo.dict_v1<{}>, #vhlo.dict_v1<{}>]>, function_type = #vhlo.type_v1<!vhlo.func_v1<(!vhlo.tensor_v1<1024x1024x!vhlo.f16_v1>, !vhlo.tensor_v1<1024x1024x!vhlo.f16_v1>) -> !vhlo.tensor_v1<1024x1024x!vhlo.f32_v1>>>, res_attrs = #vhlo.array_v1<[#vhlo.dict_v1<{#vhlo.string_v1<"jax.result_info"> = #vhlo.string_v1<"">}>]>, sym_name = #vhlo.string_v1<"main">, sym_visibility = #vhlo.string_v1<"public">}> ({
  ^bb0(%arg0: !vhlo.tensor_v1<1024x1024x!vhlo.f16_v1>, %arg1: !vhlo.tensor_v1<1024x1024x!vhlo.f16_v1>):
    %0 = "vhlo.dot_general_v2"(%arg0, %arg1) <{accumulation_type = #vhlo.type_v1<!vhlo.f32_v1>, allow_imprecise_accumulation = #vhlo.bool_v1<false>, lhs_batching_dimensions = #vhlo.tensor_v1<dense<> : tensor<0xi64>>, lhs_component_count = #vhlo.integer_v1<1 : i64>, lhs_contracting_dimensions = #vhlo.tensor_v1<dense<1> : tensor<1xi64>>, lhs_precision_type = #vhlo.type_v1<!vhlo.f16_v1>, num_primitive_operations = #vhlo.integer_v1<1 : i64>, precision_config = #vhlo.array_v1<[#vhlo<precision_v1 DEFAULT>, #vhlo<precision_v1 DEFAULT>]>, rhs_batching_dimensions = #vhlo.tensor_v1<dense<> : tensor<0xi64>>, rhs_component_count = #vhlo.integer_v1<1 : i64>, rhs_contracting_dimensions = #vhlo.tensor_v1<dense<0> : tensor<1xi64>>, rhs_precision_type = #vhlo.type_v1<!vhlo.f16_v1>}> : (!vhlo.tensor_v1<1024x1024x!vhlo.f16_v1>, !vhlo.tensor_v1<1024x1024x!vhlo.f16_v1>) -> !vhlo.tensor_v1<1024x1024x!vhlo.f32_v1>
    "vhlo.return_v1"(%0) : (!vhlo.tensor_v1<1024x1024x!vhlo.f32_v1>) -> ()
  }) : () -> ()
}) {mhlo.num_partitions = 1 : i32, mhlo.num_replicas = 1 : i32} : () -> ()
```

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.4.36.dev20241030+e35e7f8e2
jaxlib: 0.4.36.dev20241031
numpy:  1.26.4
python: 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
device info: NVIDIA H100 80GB HBM3-1, 1 local devices"
process_count: 1
platform: uname_result(system='Linux', node=<removed>, release='5.15.0-1029-nvidia', version='#29-Ubuntu SMP Mon Jul 17 15:02:31 UTC 2023', machine='x86_64')


$ nvidia-smi
Thu Oct 31 21:00:29 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA H100 80GB HBM3          On  |   00000000:1B:00.0 Off |                    0 |
| N/A   39C    P0             77W /  700W |     534MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
+-----------------------------------------------------------------------------------------+

```

**Comment by dfm** [comment] 2024-10-31 23:35
Yeah - this was broken in https://github.com/openxla/xla/pull/18713, but then fixed in https://github.com/openxla/xla/pull/18862. It looks like you've gotten unlucky with the specific nightly jaxlib you're using. I expect the next one (or maybe the one after) will have the integrated XLA.

**Comment by dfm** [comment] 2024-11-08 16:09
I've just confirmed that this seems to work fine with jaxlib 0.4.36.dev20241108 (the current nightly) and the released jaxlib 0.4.35, so I'm going to close this, but please comment or open a new issue if you run into further problems!

**Closed by dfm** 2024-11-08 16:09 UTC
Labels: bug

**Comment by andportnoy** [comment] 2024-11-08 16:16
Yes I confirm it worked for me as well with a more recent jaxlib, thanks!

**Comment by andportnoy** [comment] 2024-11-08 17:38
Modifying `out_dtype` leads to unexpected behavior though, I opened https://github.com/jax-ml/jax/issues/24794.
