### ISSUE TITLE
Large consume of memory when using jax.lax.cond

### ISSUE THREAD

**Issue by celiolarcher** [jax-ml/jax#18769] opened 2023-12-01 16:46 UTC
### Description

When using optax, I found an unexpectedly large consumption of memory in the MultiStep method (https://github.com/google-deepmind/optax/issues/472). 

Digging deeper, the problem comes from the jax.lax.cond command in this part of the code.

```python
new_updates, new_state = jax.lax.cond(
          state.mini_step < k_steps - 1,
          _mid_step, _final_step, *(state, params, acc_grads))
```

If I got it right, JAX is allocating memory for both function outputs (_mid_step and _final_step), so this basically doubles the space to store optimizer states and grads in this case.

I was able to solve it by changing the approach to avoid the jax.lax.cond command, but it seems something worth checking on the JAX/XLA side.

### What jax/jaxlib version are you using?

jax 0.4.7, jaxlib 0.4.7

### Which accelerator(s) are you using?

TPU

### Additional system info?

numpy 1.24.4, Python 3.8.10 (default, Nov 22 2023, 10:22:35),  [GCC 9.4.0], Linux uname_result(system='Linux', node='t1v-n-32f4074b-w-0', release='5.13.0-1027-gcp', version='#32~20.04.1-Ubuntu SMP Thu May 26 10:53:08 UTC 2022', machine='x86_64', processor='x86_64')

**Comment by froystig** [comment] 2024-08-07 13:03
We seem to have missed this issue until now. :/

Not having seen the error message or a reproducing example, my best guess is that what you saw here is a compile-time out-of-memory error. Is that right?

`jax.lax.cond` lowers to a conditional in HLO (the XLA compiler language). XLA schedules memory completely statically. Since it can't know which branch of a conditional is taken, it must allocate memory for either outcome.

**Comment by celiolarcher** [comment] 2024-09-22 21:03
Hi @froystig ,

Sorry for the late answer. 
> my best guess is that what you saw here is a compile-time out-of-memory error. Is that right?

There is sometime since I debug this error, but yes, I think it was a compile-time OOM.

> Since it can't know which branch of a conditional is taken, it must allocate memory for either outcome.

Yes, this seems the issue for me! I understand the reason for allocating memory for both functions, but I'm trying to think if there is a better behavior to be implemented here. Maybe allow sharing the same memory space for output vectors in both functions in case those output vectors share the same shape? IDK the complexity to do such a thing.

**Comment by froystig** [comment] 2024-09-22 21:59
> Maybe allow sharing the same memory space for output vectors in both functions in case those output vectors share the same shape? IDK the complexity to do such a thing.

That sort of common buffer optimization should already be happening when possible. We also do something similar to what you're describing for closed-over values that share shapes and dtypes among the branch functions. If you're curious, that is handled by these lines in the `cond` implementation: https://github.com/jax-ml/jax/blob/48c29f62e10b7b29d096848214701e4ae58cf31d/jax/_src/lax/control_flow/conditionals.py#L140-L141

It looks like things are fixed in Optax based on the thread there, and we don't have a reproducing example any more. Is it likely that we have resolved this entirely?

**Comment by celiolarcher** [comment] 2024-09-23 00:56
Yeah, its possible to be a non-problem by now. We could check this by trying to reproduce everything in the old version of optax, but I don't know if it's worth it and I don't have the time right now.

Perhaps close this issue and wait for new cases?

**Comment by froystig** [comment] 2024-09-23 01:38
Sounds good. Let's close now and reopen later if appropriate. Thanks for the discussion!

**Closed by froystig** 2024-09-23 01:38 UTC
Labels: bug
